language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
bundler_args: --path vendor/bundle
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
before_script:
  - cp spec/database.yml.sample spec/database.yml
script:
  - bundle exec rspec spec